await Promise.all(['Regular','Medium','Semi Bold','Bold'].map(style=>figma.loadFontAsync({family:'Inter',style})));
const created=[];
const V=Object.fromEntries((await figma.variables.getLocalVariablesAsync()).filter(v=>v.name.startsWith('color/')||v.name.startsWith('space/')||v.name.startsWith('radius/')).map(v=>[v.name,v]));
const S=Object.fromEntries((await figma.getLocalTextStylesAsync()).filter(s=>s.name.startsWith('TrailPack/')).map(s=>[s.name.split('/')[1],s]));
const buttonSet=await figma.importComponentSetByKeyAsync('cc8b558dc7d9684011b6b99ce8e6509399bc836b');
const navSet=await figma.importComponentSetByKeyAsync('1d2523aed78254402984bbbffdf9010d30b6f35c');
function track(n){created.push(n.id);return n;}
function paint(k){return figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:0,g:0,b:0}},'color',V['color/'+k]);}
function color(n,k){n.fills=[paint(k)];}
function pad(n,p){for(const s of ['Top','Right','Bottom','Left']){n['padding'+s]=p;if(V['space/'+p])n.setBoundVariable('padding'+s,V['space/'+p]);}}
function auto(parent,name,dir='VERTICAL',gap=0,w){const n=track(figma.createAutoLayout(dir));n.name=name;n.fills=[];n.itemSpacing=gap;if(V['space/'+gap])n.setBoundVariable('itemSpacing',V['space/'+gap]);if(parent)parent.appendChild(n);if(w){n.resize(w,100);n.layoutSizingHorizontal='FIXED';}return n;}
function fill(n){n.layoutSizingHorizontal='FILL';return n;}
function fixed(n,w,h){n.resize(w,h);n.layoutSizingHorizontal='FIXED';n.layoutSizingVertical='FIXED';return n;}
function round(n){n.cornerRadius=8;for(const k of ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius'])n.setBoundVariable(k,V['radius/control']);}
function text(parent,value,style='Body',tone='foreground',w){const n=track(figma.createText());n.name=value.slice(0,60);n.fontName={family:'Inter',style:'Regular'};n.characters=value;n.textStyleId=S[style].id;color(n,tone);parent.appendChild(n);n.textAutoResize='WIDTH_AND_HEIGHT';if(w){n.resize(w,n.height);n.textAutoResize='HEIGHT';}return n;}
function rule(parent){const n=track(figma.createRectangle());n.name='Divider';n.resize(10,1);color(n,'border');parent.appendChild(n);n.layoutSizingHorizontal='FILL';return n;}
function btn(parent,label,variant='Primary',width){const main=buttonSet.children.find(n=>n.type==='COMPONENT'&&n.name===`Variant=${variant}, State=Default, Size=Medium`);const n=track(main.createInstance());parent.appendChild(n);n.setProperties({'Label#2:0':label,'Has Icon Start#4:128':false,'Has Icon End#4:64':false});n.name='Action / '+label;n.resize(width||Math.max(100,label.length*8+32),48);n.layoutSizingHorizontal='FIXED';n.layoutSizingVertical='FIXED';round(n);color(n,variant==='Primary'?'action':'surface');n.strokes=variant==='Primary'?[]:[paint('border')];n.findAllWithCriteria({types:['TEXT']}).forEach(t=>{t.fontName={family:'Inter',style:'Semi Bold'};t.fontSize=14;color(t,variant==='Primary'?'inverse':'action');});return n;}
const paths={mountain:'M3 20 10 5l4 7 2-4 5 12H3Zm5-11 3 3 2-2',explore:'M21 21l-4.35-4.35M11 18a7 7 0 100-14 7 7 0 000 14z',trips:'M9 20l-6-3V5l6 2 6-3 6 3v13l-6-3-6 3Zm0 0V7m6 10V4',gear:'M8 7V5a4 4 0 018 0v2M6 7h12l2 14H4L6 7Zm2 7h8v4H8v-4',profile:'M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z',record:'M12 3a9 9 0 100 18 9 9 0 000-18Zm0 5a4 4 0 100 8 4 4 0 000-8Z',chevron:'m9 5 7 7-7 7',check:'m5 12 4 4 10-10'};
function icon(parent,name,tone='inverse',size=24){const hex=tone==='inverse'?'#ffffff':tone==='muted'?'#59665e':'#245b47';const n=track(figma.createNodeFromSvg(`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="${paths[name]}" stroke="${hex}" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`));n.name='Icon / '+name;parent.appendChild(n);return n;}
function nav(parent,label,active=false,mobile=false){const d=mobile?'Column':'Row';const main=navSet.children.find(n=>n.type==='COMPONENT'&&n.name===`State=${active?'Active':'Default'}, Direction=${d}, Type=Medium`);const n=track(main.createInstance());parent.appendChild(n);n.setProperties({'Label#515:1':label,'Has Icon#515:5':false});n.name='Navigate / '+label;n.resize(mobile?82:192,mobile?48:52);n.layoutSizingHorizontal='FIXED';n.layoutSizingVertical='FIXED';n.fills=active?[paint(mobile?'soft':'selected')]:[];n.strokes=[];round(n);n.findAllWithCriteria({types:['TEXT']}).forEach(t=>{t.fontName={family:'Inter',style:active?'Semi Bold':'Regular'};t.fontSize=mobile?12:16;color(t,mobile?(active?'action':'muted'):(active?'inverse':'inverse-muted'));});return n;}
function shell(name,x,y,active='My trips',mobile=false){const root=auto(null,name,mobile?'VERTICAL':'HORIZONTAL',0);root.x=x;root.y=y;fixed(root,mobile?390:1536,mobile?844:1024);root.clipsContent=true;color(root,'background');let main;
if(!mobile){const rail=auto(root,'Navigation','VERTICAL',24,240);fixed(rail,240,1024);color(rail,'forest');pad(rail,24);const brand=auto(rail,'Brand','HORIZONTAL',12);brand.counterAxisAlignItems='CENTER';icon(brand,'mountain');text(brand,'TrailPack','Subheading','inverse');const items=fill(auto(rail,'Destinations','VERTICAL',8));items.paddingTop=24;for(const label of ['Explore','My trips','Gear'])nav(items,label,label===active);const spacer=fill(auto(rail,'Flexible space'));spacer.layoutSizingVertical='FILL';btn(rail,'Record activity','Neutral',192);nav(rail,'Profile');main=auto(root,'Workspace','VERTICAL',20,1296);fixed(main,1296,1024);pad(main,32);main.paddingLeft=48;main.paddingRight=32;}
else {const header=fill(auto(root,'Mobile header','HORIZONTAL',12));pad(header,20);color(header,'forest');header.counterAxisAlignItems='CENTER';icon(header,'mountain');const word=text(header,'TrailPack','Subheading','inverse');word.layoutSizingHorizontal='FILL';icon(header,'profile');main=fill(auto(root,'Workspace','VERTICAL',20));pad(main,20);main.layoutSizingVertical='FILL';main.clipsContent=true;const bottom=fill(auto(root,'Bottom navigation','HORIZONTAL',8));pad(bottom,12);color(bottom,'surface');bottom.primaryAxisAlignItems='SPACE_BETWEEN';for(const label of ['Explore','My trips','Gear','Profile'])nav(bottom,label,label===active,true);}
return {root,main};}
function stage(parent,active,mobile=false){const row=fill(auto(parent,'Trip progress','HORIZONTAL',mobile?12:32));row.counterAxisAlignItems='CENTER';row.paddingTop=8;row.paddingBottom=8;['Choose a trail','Prepare your pack','Record your outing'].forEach((label,i)=>{const group=auto(row,'Step '+(i+1),'HORIZONTAL',8);group.counterAxisAlignItems='CENTER';if(!mobile)group.layoutSizingHorizontal='FILL';const number=auto(group,'Step indicator','HORIZONTAL',0);fixed(number,32,32);number.cornerRadius=16;color(number,i===active?'action':'soft');number.primaryAxisAlignItems='CENTER';number.counterAxisAlignItems='CENTER';text(number,String(i+1),'Label',i===active?'inverse':'muted');if(!mobile||i===active)text(group,mobile?['Trail','Your pack','Record'][i]:label,'Label',i===active?'foreground':'muted');});return row;}
function panel(parent,name,w,bg='surface'){const n=auto(parent,name,'VERTICAL',16,w);pad(n,24);color(n,bg);round(n);return n;}
function allIds(roots){return Array.from(new Set([...created,...roots.flatMap(n=>[n.id,...n.findAll(()=>true).map(c=>c.id)])]));}
